title: Tabula Rasa
description: "The machines survived. The software didn't."
baseurl: "/axiom-blog"
url: "https://adamclements.github.io"

theme: minima

author:
  name: Axiom Systems — Field Communications Division

defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"

plugins:
  - jekyll-feed
  - jekyll-seo-tag
